# Generated by Django 4.2 on 2024-06-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='KarbaranTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام و نام خانوادگی')),
                ('photo', models.ImageField(upload_to='images', verbose_name='عکس کاربر')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'لیست کاربران',
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'لیست پروفایل'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(upload_to='images', verbose_name='عکس پروفایل'),
        ),
    ]
